accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignUpView

# from .views import SignUpView

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
]

projects/urls.py
from projects.views import (
    ProjectCreateView,
    ProjectDetailView,
    ProjectListView,
    ProjectSearchResultView,
)

from django.urls import path

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
    path("search/", ProjectSearchResultView.as_view(), name="search_results"),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    TaskCreateView,
    TaskListView,
    TaskSearchListView,
    TaskUpdateView,
)

urlpatterns = [
    path(
        "create/<int:project_id>", TaskCreateView.as_view(), name="create_task"
    ),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("search/", TaskSearchListView.as_view(), name="search_taskresults"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL, null=True, related_name="tasks", on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

tasks/forms.py
from django.forms import ModelForm
from tasks.models import Task
from projects.models import Project
from django.contrib.auth.models import User


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["name", "start_date", "due_date", "project", "assignee"]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        # project_members = kwargs.pop("project_members")
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields["project"].queryset = Project.objects.filter(members=user)
        # self.fields["assignee"].queryset = Project.objects.filter(
        #     members=project_members[0]
        # )

    # stackoverflow attempt
    # def form_valid(self, form):
    #     form.instance.project_id = Project.self.kwargs["project_id"]
    #     return super(TaskForm, self).form_valid(form)

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("home")
    template_name = "registration/signup.html"

    def form_valid(self, form):
        to_return = super().form_valid(form)
        login(self.request, self.object)
        return to_return

projects/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from projects.models import Project
from tasks.models import Task
from django.db.models import Exists, OuterRef, Q

# Create your views here.
class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        queryset = Project.objects.filter(members=self.request.user)
        # tested above to see if this will filter projects based off of user and it does work
        subquery = Task.objects.filter(
            project=OuterRef("pk"), is_completed=False
        )
        queryset = queryset.annotate(all_completed=~Exists(subquery))
        return queryset


class ProjectSearchResultView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/search.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Project.objects.filter(
            Q(name__icontains=query), members=self.request.user
        )
        return object_list


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"
    context_object_name = "project"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])

tasks/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.forms import TaskForm
from tasks.models import Task
from projects.models import Project
from django.db.models import OuterRef
from django.contrib.auth import get_user_model
from django.db.models import Q


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"

    form_class = TaskForm

    def get_form_kwargs(self):
        kwargs = super(TaskCreateView, self).get_form_kwargs()
        kwargs["user"] = self.request.user

        # Attempt #1: assignee list has list of projects
        # when trying to print Project.values only name and description show up. Maybe user is protected?
        # kwargs["project_members"] = Project.objects.values_list(
        #     "pk", flat=Truep
        # )

        # Attempt #2: nothing shows up in assignee list
        # kwargs["project_id"] = Project.objects.all()[0].members.name
        # print(Project.objects.all()[0].members)  # prints auth.User.none
        return kwargs

    # stackoverflow attempt
    # def get_form(self, *args, **kwargs):
    #     form = super(TaskCreateView, self).get_form(*args, **kwargs)
    #     form.fields["assignee"].queryset = Project.members.filter(
    #         project_id=self.kwargs["project_id"]
    #     )

    def get_success_url(self):
        return reverse_lazy("show_my_tasks")


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/mytaskslist.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskSearchListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/search.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Task.objects.filter(
            Q(name__icontains=query), assignee=self.request.user
        )
        return object_list


class TaskUpdateView(UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Projects</title>
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">
                                My projects
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">
                                Logout
                            </a>
                        </li>
                        {% if user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}">
                                Admin
                            </a>
                        </li>
                        {% endif %}
                    {% else %}
                        <a href="{% url 'login' %}">
                            Login
                        </a>
                        <li>
                            <a href="{% url 'signup' %}">
                                Signup
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="project-form">
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button">Create</button>
            </form>
            <button><a href="{% url 'list_projects'  %}">Back to all projects</a></button>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% block content %}
    <main>
        <div class="project-detail">
            <h1>{{ project.name }} </h1>
            {{ project.description|markdownify }}

            <h2>Tasks</h2>
            <p><a href="{% url 'create_task' project.pk %}">Create a new task</a></p>
            {% if project.tasks.all|length > 0  %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                        <tr>
                            
                                <td>{{task.name}}</td>
                                <td>{{task.assignee}}</td>
                                <td>{{task.start_date}}</td>
                                <td>{{task.due_date}}</td>
                                <td>{% if task.is_completed%}
                                    yes
                                {% else %}
                                    no
                                {% endif %}
                           
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>

                </table>
            {% else %}
                <p>This project has no tasks</p>
            {% endif %}


        </div>
        {% comment %} <a href="{% url '' %}"><button>Create a list</button></a>
        {% endcomment %}
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="project-list">
            <h1>My Projects:</h1>
            <p><a href="{% url 'create_project' %}">Create a new project</a></p>
            <div><form action="{% url 'search_results' %}" method="get">
                <input name="q" type="text" placeholder="Search by project name">
                <button>Search</button>
              </form>
            </div> 
            {% if project_list %}

                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                            <th>All tasks in project complete?</th>
                        </tr>
                    </thead>
                    {% for projects in project_list %}
                        <tbody>
                            <tr>
                                <td><a href="{% url 'show_project' projects.pk %}"> {{ projects.name }}</a> </td>
                                <td>{{ projects.tasks.all|length }}</td>
                                <td>{% if projects.all_completed == True %} 
                                    Yes 
                                    {% else %}
                                    No 
                                    {% endif %}
                                </td>
                            </tr>
                        </tbody>
                    {% endfor %}
                </table>
            {% else %}
                <p>You are not assigned to any projects</p>
            {% endif %}
        </div>

        {% comment %} <a href="{% url '' %}"><button>Create a new item for a list</button></a>  {% endcomment %}
    </main>
{% endblock content %}

projects/templates/projects/search.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>My Projects: Search Results</h1>
            <p><a href="{% url 'create_project' %}">Create a new project</a></p>
            <ul>
                {% if object_list %}
                {% for project in object_list %}
                  <li>
                    <a href="{% url 'show_project' project.pk %}">{{ project.name }}</a>
                  </li>
                
                {% endfor %}
              </ul>
                <div><form action="{% url 'search_results' %}" method="get">
                  <input name="q" type="text" placeholder="Search by project name">
                  <button>Search</button>
                </form>
              </div> 
                {% else %}
                <p>No projects for your search result. Try something else?</p>
                <div><form action="{% url 'search_results' %}" method="get">
                  <input name="q" type="text" placeholder="Search by project name">
                  <button>Search</button>
                </form>
              </div> 
                {% endif %}

              
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="task-form">
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button">Create</button>
            </form>
            <button><a href="{% url 'list_projects'  %}">Back to all projects</a></button>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/mytaskslist.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="my-tasks-list">
            <h1>My Tasks:</h1>
            <div><form action="{% url 'search_taskresults' %}" method="get">
                <input name="q" type="text" placeholder="Search by task name">
                <button>Search</button>
              </form>
            </div> 
            {% if task_list|length > 0 %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Project</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    
                        <tbody>
                            {% for task in task_list %}
                            <tr>
                                
                                <td>{{ task }} </td>
                                <td>{{ task.project }} </td>
                                <td>{{ task.start_date }}</td>
                                <td>{{task.due_date }} </td>
                                <td>{% if task.is_completed%}
                                    Done
                                {% else %}
                                    <form method="post" action="{% url 'complete_task' task.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Complete</button>
                                    </form>
                                {% endif %}
                                </td>
                               
                            </tr>
                            {% endfor %}
                           
                        </tbody>
                        
                </table>
            {% else %}
                <p>You have no tasks</p>
            {% endif %}
        </div>

        {% comment %} <a href="{% url '' %}"><button>Create a new item for a list</button></a>  {% endcomment %}
    </main>
{% endblock content %}

tasks/templates/tasks/search.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>My Projects: Search Results</h1>
            <p><a href="{% url 'create_project' %}">Create a new project</a></p>
            <ul>
                {% if object_list %} 
                {% for task in object_list %}
                  <li>
                    {{ task.name }}
                  </li>
                {% endfor %}
              </ul>
                <div><form action="{% url 'search_taskresults' %}" method="get">
                  <input name="q" type="text" placeholder="Search by task name">
                  <button>Search</button>
                </form>
              </div> 
                 {% else %}
                <p>No tasks for your search result. Try something else?</p>
                <div><form action="{% url 'search_taskresults' %}" method="get">
                  <input name="q" type="text" placeholder="Search by task name">
                  <button>Search</button>
                </form>
              </div> 
                {% endif %} 

              
        </div>
    </main>
{% endblock content %}